spring.application.name=trace-distrubute-tracing

#This will start Zipkin on port 9411 by default. This ensures Zipkin runs on the standard port.
server.port: 9411

# Optional: Set logging level for debugging
logging.level.zipkin2=INFO
logging.level.org.springframework=INFO

# Optional: Enable Armeria server on port 9411 if you're using Armeria
armeria.ports[0].port=9412
armeria.ports[0].protocols=http

#Enable Bean Overriding
spring.main.allow-bean-definition-overriding: true

##Eureka server client auto-register
##Access Step 1 or Step 2. This will be accessible using ip-address
#eureka.instance.prefer-ip-address=true
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
##Access Step 1 or Step 2. This will be accessible using localhost
#eureka.instance.hostname=localhost
#eureka.instance.instance-id=${spring.application.name}:localhost:${server.port}
#
##configure below property to automatically register with the Eureka Server
#eureka.client.service-url.defaultZone=${EUREKA_SERVER_ADDRESS:http://localhost:8751/eureka}	