spring.application.name=trace-distrubute-tracing

#This will start Zipkin on port 9411 by default. This ensures Zipkin runs on the standard port.
server.port: 9411

# Optional: Set logging level for debugging
logging.level.zipkin2=INFO
logging.level.org.springframework=INFO

# Optional: Enable Armeria server on port 9411 if you're using Armeria
armeria.ports[0].port=9411
armeria.ports[0].protocols=http

#Enable Bean Overriding
spring.main.allow-bean-definition-overriding: true

